export default Object.freeze({
	root: {
		LOGIN: 'LOGIN',
		SET_CONFIG: 'SET_CONFIG',
	},
	decks: {
		INIT: 'INIT',
		LOADED: 'LOADED',
		UPDATE: 'UPDATE',
		UPDATE_CARDS: 'UPDATE_CARDS',
	},
	game: {
		LOADED: 'LOADED',
		INIT: 'INIT',
		UPDATE: 'UPDATE',
	},
	players: {
		DRAW_CARD: 'DRAW_CARD',
		UPDATE: 'UPDATE',
		UPDATE_CARDS: 'UPDATE_CARDS',
	},
	sounds: {
		TOGGLE: 'TOGGLE',
	},
	start: {
		ADD_GAME: 'ADD_GAME',
		DELETE_GAME: 'DELETE_GAME',
		GAME_CREATE: 'GAME_CREATE',
		GAME_DELETE: 'GAME_DELETE',
		GAMES_CLEAR: 'GAMES_CLEAR',
		GAMES_LOAD: 'GAMES_LOAD',
	},
	websocket: {
		SOCKET_ONOPEN: 'SOCKET_ONOPEN',
		SOCKET_ONCLOSE: 'SOCKET_ONCLOSE',
		SOCKET_ONERROR: 'SOCKET_ONERROR',
		SOCKET_ONMESSAGE: 'SOCKET_ONMESSAGE',
		SOCKET_RECONNECT: 'SOCKET_RECONNECT',
		SOCKET_RECONNECT_ERROR: 'SOCKET_RECONNECT_ERROR',
	},
});
